<template>
<div>
        <scroll class="content">
        <ul>
            <li>小时行驶时1</li>
            <li>小时行驶时2</li>
            <li>小时行驶时3</li>
            <li>小时行驶时4</li>
            <li>小时行驶时5</li>
            <li>小时行驶时6</li>
            <li>小时行驶时7</li>
            <li>小时行驶时8</li>
            <li>小时行驶时9</li>
            <li>小时行驶时10</li>
            <li>小时行驶时11</li>
            <li>小时行驶时12</li>
            <li>小时行驶时13</li>
            <li>小时行驶时14</li>
            <li>小时行驶时15</li>
            <li>小时行驶时16</li>
            <li>小时行驶时17</li>
            <li>小时行驶时18</li>
            <li>小时行驶时19</li>
            <li>小时行驶时20</li>
            <li>小时行驶时21</li>
            <li>小时行驶时22</li>
            <li>小时行驶时23</li>
            <li>小时行驶时24</li>
            <li>小时行驶时25</li>
            <li>小时行驶时26</li>
            <li>小时行驶时27</li>
            <li>小时行驶时28</li>
            <li>小时行驶时29</li>
            <li>小时行驶时30</li>
            <li>小时行驶时31</li>
            <li>小时行驶时32</li>
            <li>小时行驶时33</li>
            <li>小时行驶时34</li>
            <li>小时行驶时35</li>
            <li>小时行驶时36</li>
            <li>小时行驶时37</li>
            <li>小时行驶时38</li>
            <li>小时行驶时39</li>
            <li>小时行驶时40</li>
            <li>小时行驶时41</li>
            <li>小时行驶时42</li>
            <li>小时行驶时43</li>
            <li>小时行驶时44</li>
            <li>小时行驶时45</li>
            <li>小时行驶时46</li>
            <li>小时行驶时47</li>
            <li>小时行驶时48</li>
            <li>小时行驶时49</li>
            <li>小时行驶时50</li>
            <li>小时行驶时51</li>
            <li>小时行驶时52</li>
            <li>小时行驶时53</li>
            <li>小时行驶时54</li>
            <li>小时行驶时55</li>
            <li>小时行驶时56</li>
            <li>小时行驶时57</li>
            <li>小时行驶时58</li>
            <li>小时行驶时59</li>
            <li>小时行驶时60</li>
            <li>小时行驶时61</li>
            <li>小时行驶时62</li>
            <li>小时行驶时63</li>
            <li>小时行驶时64</li>
            <li>小时行驶时65</li>
            <li>小时行驶时66</li>
            <li>小时行驶时67</li>
            <li>小时行驶时68</li>
            <li>小时行驶时69</li>
            <li>小时行驶时70</li>
            <li>小时行驶时71</li>
            <li>小时行驶时72</li>
            <li>小时行驶时73</li>
            <li>小时行驶时74</li>
            <li>小时行驶时75</li>
            <li>小时行驶时76</li>
            <li>小时行驶时77</li>
            <li>小时行驶时78</li>
            <li>小时行驶时79</li>
            <li>小时行驶时80</li>
            <li>小时行驶时81</li>
            <li>小时行驶时82</li>
            <li>小时行驶时83</li>
            <li>小时行驶时84</li>
            <li>小时行驶时85</li>
            <li>小时行驶时86</li>
            <li>小时行驶时87</li>
            <li>小时行驶时88</li>
            <li>小时行驶时89</li>
            <li>小时行驶时90</li>
            <li>小时行驶时91</li>
            <li>小时行驶时92</li>
            <li>小时行驶时93</li>
            <li>小时行驶时94</li>
            <li>小时行驶时95</li>
            <li>小时行驶时96</li>
            <li>小时行驶时97</li>
            <li>小时行驶时98</li>
            <li>小时行驶时99</li>
            <li>小时行驶时100</li>
        </ul>
    </scroll>
</div>
</template>

<script>
import Scroll from 'components/common/scroll/Scroll'
export default {
 name:"ProFile",
 components:{
     Scroll
 }
}
</script>

<style scoped>
.content {
    height: calc(100vh - 49px);
}
</style>